/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppPaperPaperIdRouteImport } from './routes/app.paper.$paperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/app/library',
  path: '/app/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/app/knowledge',
  path: '/app/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/app/compare',
  path: '/app/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/app/activity',
  path: '/app/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaperPaperIdRoute = AppPaperPaperIdRouteImport.update({
  id: '/app/paper/$paperId',
  path: '/app/paper/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/compare': typeof AppCompareRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/library': typeof AppLibraryRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/paper/$paperId': typeof AppPaperPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/compare': typeof AppCompareRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/library': typeof AppLibraryRoute
  '/app/projects': typeof AppProjectsRoute
  '/app': typeof AppIndexRoute
  '/app/paper/$paperId': typeof AppPaperPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/compare': typeof AppCompareRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/library': typeof AppLibraryRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/paper/$paperId': typeof AppPaperPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/activity'
    | '/app/compare'
    | '/app/knowledge'
    | '/app/library'
    | '/app/projects'
    | '/app/'
    | '/app/paper/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/activity'
    | '/app/compare'
    | '/app/knowledge'
    | '/app/library'
    | '/app/projects'
    | '/app'
    | '/app/paper/$paperId'
  id:
    | '__root__'
    | '/'
    | '/app/activity'
    | '/app/compare'
    | '/app/knowledge'
    | '/app/library'
    | '/app/projects'
    | '/app/'
    | '/app/paper/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppActivityRoute: typeof AppActivityRoute
  AppCompareRoute: typeof AppCompareRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPaperPaperIdRoute: typeof AppPaperPaperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/library': {
      id: '/app/library'
      path: '/app/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/app/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/app/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/app/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/paper/$paperId': {
      id: '/app/paper/$paperId'
      path: '/app/paper/$paperId'
      fullPath: '/app/paper/$paperId'
      preLoaderRoute: typeof AppPaperPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppActivityRoute: AppActivityRoute,
  AppCompareRoute: AppCompareRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPaperPaperIdRoute: AppPaperPaperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
